receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: " http://otel-collector:4317" # e.g.,

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans" # Assuming Zipkin is running in another container

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin, otlp]

    metrics:
      receivers: [otlp]
      exporters: [otlp]

extensions:
  health_check: {}