receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp:
    endpoint: "http://otel-collector:4317" # e.g.,

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans" # Assuming Zipkin is running in another container
  
  prometheus:
    endpoint: 0.0.0.0:9000
 
  otlphttp:
    endpoint: http://loki:3100/otlp

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin, otlp]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      exporters: [otlphttp]


extensions:
  health_check: {}

processors:
  batch: